[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#e7ecf0"
secondaryBackgroundColor = "#e2dcdc"
textColor = "#1a202c"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = true